name: "setup pip"
description: "Setup pip cache & install"

runs:
  using: "composite"
  steps:
    - name: pip cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          ${{ runner.os }}-pip-
    - run: pip3 install -r ./requirements.txt
      shell: bash
