name: Release CI

on:
  push:
    tags: "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-yarn
      - name: Set env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "RELEASE_NAME=${RELEASE_VERSION:1}" >> $GITHUB_ENV
      - name: Publish to NPM
        run: |
          # Publish
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          yarn workspaces foreach run publish
      - name: Zip
        run: |
          cd packages

          # Remove Split Files
          find -wholename "**/webfonts/*/split*" -delete

          # Zip
          (cd wanted-sans/fonts && zip -rv - .) > WantedSans-${{ env.RELEASE_NAME }}.zip
          (cd wanted-sans-std/fonts && zip -rv - .) > WantedSansStd-${{ env.RELEASE_NAME }}.zip
      - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            packages/WantedSans-${{ env.RELEASE_NAME }}.zip
            packages/WantedSansStd-${{ env.RELEASE_NAME }}.zip
